
server:
  port: 9101

spring:
  application:
    name: qaq-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
